package com.example.winderif.ehentaiapp;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.example.winderif.ehentaiapp.GallerysToTags;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table GALLERYS_TO_TAGS.
*/
public class GallerysToTagsDao extends AbstractDao<GallerysToTags, Void> {

    public static final String TABLENAME = "GALLERYS_TO_TAGS";

    /**
     * Properties of entity GallerysToTags.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property GalleryId = new Property(0, long.class, "galleryId", false, "GALLERY_ID");
        public final static Property TagId = new Property(1, long.class, "tagId", false, "TAG_ID");
    };

    private DaoSession daoSession;

    private Query<GallerysToTags> gallery_TagsQuery;

    public GallerysToTagsDao(DaoConfig config) {
        super(config);
    }
    
    public GallerysToTagsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GALLERYS_TO_TAGS' (" + //
                "'GALLERY_ID' INTEGER NOT NULL ," + // 0: galleryId
                "'TAG_ID' INTEGER NOT NULL );"); // 1: tagId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GALLERYS_TO_TAGS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GallerysToTags entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getGalleryId());
        stmt.bindLong(2, entity.getTagId());
    }

    @Override
    protected void attachEntity(GallerysToTags entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public GallerysToTags readEntity(Cursor cursor, int offset) {
        GallerysToTags entity = new GallerysToTags( //
            cursor.getLong(offset + 0), // galleryId
            cursor.getLong(offset + 1) // tagId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GallerysToTags entity, int offset) {
        entity.setGalleryId(cursor.getLong(offset + 0));
        entity.setTagId(cursor.getLong(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(GallerysToTags entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(GallerysToTags entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "tags" to-many relationship of Gallery. */
    public List<GallerysToTags> _queryGallery_Tags(long galleryId) {
        synchronized (this) {
            if (gallery_TagsQuery == null) {
                QueryBuilder<GallerysToTags> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.GalleryId.eq(null));
                gallery_TagsQuery = queryBuilder.build();
            }
        }
        Query<GallerysToTags> query = gallery_TagsQuery.forCurrentThread();
        query.setParameter(0, galleryId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTagDao().getAllColumns());
            builder.append(" FROM GALLERYS_TO_TAGS T");
            builder.append(" LEFT JOIN TAG T0 ON T.'TAG_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected GallerysToTags loadCurrentDeep(Cursor cursor, boolean lock) {
        GallerysToTags entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Tag tag = loadCurrentOther(daoSession.getTagDao(), cursor, offset);
         if(tag != null) {
            entity.setTag(tag);
        }

        return entity;    
    }

    public GallerysToTags loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<GallerysToTags> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<GallerysToTags> list = new ArrayList<GallerysToTags>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<GallerysToTags> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<GallerysToTags> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
