package com.example.winderif.ehentaiapp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TAG.
 */
public class Tag {

    private Long id;
    /** Not-null value. */
    private String name;
    private Integer count;
    private java.util.Date lastRead;
    private java.util.Date latest;
    private Integer latestCount;
    private Boolean subscribed;

    public Tag() {
    }

    public Tag(Long id) {
        this.id = id;
    }

    public Tag(Long id, String name, Integer count, java.util.Date lastRead, java.util.Date latest, Integer latestCount, Boolean subscribed) {
        this.id = id;
        this.name = name;
        this.count = count;
        this.lastRead = lastRead;
        this.latest = latest;
        this.latestCount = latestCount;
        this.subscribed = subscribed;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public java.util.Date getLastRead() {
        return lastRead;
    }

    public void setLastRead(java.util.Date lastRead) {
        this.lastRead = lastRead;
    }

    public java.util.Date getLatest() {
        return latest;
    }

    public void setLatest(java.util.Date latest) {
        this.latest = latest;
    }

    public Integer getLatestCount() {
        return latestCount;
    }

    public void setLatestCount(Integer latestCount) {
        this.latestCount = latestCount;
    }

    public Boolean getSubscribed() {
        return subscribed;
    }

    public void setSubscribed(Boolean subscribed) {
        this.subscribed = subscribed;
    }

}
